### ISSUE TITLE
Add extension version to sentinel

### ISSUE THREAD

**Issue by gsimone** [codesandbox/open-in-codesandbox#4]
This would be marginally useful when debugging extension problems 

https://github.com/codesandbox/open-in-codesandbox/blob/b4b1639cddf1a1832beb4473b8301d861272a57c/action.yml#L13

**Comment by aj-foster** [comment]
How would you feel about including it in a separate HTML comment? That way, if we version the action while a PR is open, the description won't get two sets of links when someone pushes additional commits.

**Comment by gsimone** [comment]
Good point

**Comment by aj-foster** [comment]
Closing in favor of GitHub App.
